/* eslint-disable @next/next/no-page-custom-font */

import Head from 'next/head';
import { GlobalStyle } from '../src/theme/GlobalStyle';

function MyApp({ Component, pageProps }) {
  return (
   <>
     <Head>
        <title>UOL Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://hp.imguol.com.br/c/home/layout/vueland/icons/geral/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>
      <GlobalStyle />
      <Component {...pageProps} />
   </>
  )
}

export default MyApp
